#ifndef _OWAVEDEFORMER_H_
#define _OWAVEDEFORMER_H_

enum {
    Owavedeformer = 10000,
    WAVE_TWIST_AMOUNT,
    WAVE_WIDTH,
    WAVE_LENGTH,
    WAVE_FALLOFF,
    WAVE_TEXTURE,
    WAVE_TEXTURE_OFFSET,
    WAVE_BEND,
    ID_ADVANCED,
    WAVE_USE_LENGTH_FALLOFF,
    WAVE_LENGTH_FALLOFF,
    WAVE_USE_MASK,
    WAVE_MASK,
    ID_PREVIEW,
    WAVE_PREVIEW,
    WAVE_SIZE_PREVIEW,
};
#endif